### ISSUE TITLE
Few questions regarding the code

### ISSUE THREAD

**Issue by enter802** [TUMFTM/GraphBasedLocalTrajectoryPlanner#4]
1. For the standard/minimum example, is it possible to get the trajectory for a particular horizon (e.g. `T= 10` seconds with sampling time `0.1 second`)? 

2. The `traj_set` variable has the trajectories stored for different actions (`right`, `left`, etc.), and these trajectories contain 7 columns. I could not find the description of these columns. And what does the total row number represent?

3. Is there a code to generate the csv trajectory files (stored in `inputs\traj_ltpl_cl`)? 

Thank you in advance for your feedback and time.

**Comment by StahlTim** [comment]
I'll try to cover your questions:

1. The planning horizon is specified in graph layers or meters, specified in the [config file](https://github.com/TUMFTM/GraphBasedLocalTrajectoryPlanner/blob/master/params/ltpl_config_offline.ini#L43), e.g.  `min_plan_horizon=300` for at least 300 meters.

2. The trajectory set is described in the [documentation](https://graphbasedlocaltrajectoryplanner.readthedocs.io/en/latest/software/basics.html), i.e.:

> Each list of trajectories might be an empty set or one (default) to multiple trajectories. Each trajectory in this list is an numpy array with the columns [s, x, y, heading, curvature, vx, ax].

3. See [this repo](https://github.com/TUMFTM/global_racetrajectory_optimization) as stated in the readme/documentation.

If these answers did help, close this issue, otherwise feel free to ask further questions.

**Comment by enter802** [comment]
Thanks a lot. These really helped.

One last question though: does the loop for the standard/minimal example represent time step? If so, what would be that time step value and where can this be defined? If not, what exactly the loop represent?

**Comment by StahlTim** [comment]
> Does the loop for the standard/minimal example represent time step? If so, what would be that time step value and where can this be defined? If not, what exactly the loop represent?

A loop is the calculation of a new trajectory set based on the current state and environmental contraints. Loops are executed one after another (as fast as possible, i.e. dependent on the parameterization [e.g. a far planning horizon is computationally more demanding] and computation hardware).

**Comment by enter802** [comment]
Thanks for your prompt responses. Hopefully, I can get it working for my project
